### ISSUE TITLE
Fix describe function

### ISSUE THREAD

**Issue by zilbermanor** [mlrun/functions#9]
When running the describe function with `mlrun/mlrun-models:0.4.5` the following error occurs:

During handling of the above exception, another exception occurred:
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/mlrun/runtimes/local.py", line 179, in exec_from_params
    val = handler(*args_list)
  File "main.py", line 53, in describe
    snsplt = sns.pairplot(table, hue=label_column)
  File "/opt/conda/lib/python3.7/site-packages/seaborn/axisgrid.py", line 2121, in pairplot
    grid.map_diag(kdeplot, **diag_kws)
  File "/opt/conda/lib/python3.7/site-packages/seaborn/axisgrid.py", line 1490, in map_diag
    func(data_k, label=label_k, color=color, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/seaborn/distributions.py", line 705, in kdeplot
    cumulative=cumulative, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/seaborn/distributions.py", line 295, in _univariate_kdeplot
    cumulative=cumulative)
  File "/opt/conda/lib/python3.7/site-packages/seaborn/distributions.py", line 367, in _statsmodels_univariate_kde
    kde.fit(kernel, bw, fft, gridsize=gridsize, cut=cut, clip=clip)
  File "/opt/conda/lib/python3.7/site-packages/statsmodels/nonparametric/kde.py", line 140, in fit
    clip=clip, cut=cut)
  File "/opt/conda/lib/python3.7/site-packages/statsmodels/nonparametric/kde.py", line 453, in kdensityfft
    bw = bandwidths.select_bandwidth(X, bw, kern) # will cross-val fit this pattern?
  File "/opt/conda/lib/python3.7/site-packages/statsmodels/nonparametric/bandwidths.py", line 174, in select_bandwidth
    raise RuntimeError(err)
RuntimeError: Selected KDE bandwidth is 0. Cannot estimate density.
```

Function yaml:
```
kind: job
metadata:
  name: describe
  tag: ''
  hash: 5eb3219b3dd8c944bf6427ad37de31511c07d944
  project: network-operations
  labels:
    author: yjb
    stage: development
  categories:
  - models
  - graphics
spec:
  command: ''
  args: []
  image: mlrun/ml-models:0.4.5
  volumes:
  - flexVolume:
      driver: v3io/fuse
      options:
        accessKey: <...>
        container: users
        subPath: /admin
    name: v3io
  volume_mounts:
  - mountPath: /User
    name: v3io
  env:
  - name: V3IO_API
    value: v3io-webapi.default-tenant.svc:8081
  - name: V3IO_USERNAME
    value:  <...>
  - name: V3IO_ACCESS_KEY
    value: <...>
  default_handler: describe
  description: ''
  build:
    functionSourceCode: IyBHZW5lcmF0ZWQgYnkgbnVjbGlvLmV4cG9ydC5OdWNsaW9FeHBvcnRlciBvbiAyMDIwLTAzLTE3IDE1OjQzCgppbXBvcnQgb3MKaW1wb3J0IG51bXB5IGFzIG5wCmltcG9ydCBwYW5kYXMgYXMgcGQKaW1wb3J0IG1hdHBsb3RsaWIucHlwbG90IGFzIHBsdAppbXBvcnQgc2VhYm9ybiBhcyBzbnMKCmZyb20gbWxydW4uZXhlY3V0aW9uIGltcG9ydCBNTENsaWVudEN0eApmcm9tIG1scnVuLmRhdGFzdG9yZSBpbXBvcnQgRGF0YUl0ZW0KZnJvbSBtbHJ1bi5hcnRpZmFjdHMgaW1wb3J0IFBsb3RBcnRpZmFjdCwgVGFibGVBcnRpZmFjdAoKZnJvbSBza2xlYXJuLnByZXByb2Nlc3NpbmcgaW1wb3J0IFN0YW5kYXJkU2NhbGVyCmZyb20geWVsbG93YnJpY2sgaW1wb3J0IENsYXNzQmFsYW5jZQoKZnJvbSB0eXBpbmcgaW1wb3J0IElPLCBBbnlTdHIsIFVuaW9uLCBMaXN0LCBPcHRpb25hbAoKcGQuc2V0X29wdGlvbigiZGlzcGxheS5mbG9hdF9mb3JtYXQiLCBsYW1iZGEgeDogIiUuMmYiICUgeCkKCmRlZiBfZ2NmX2NsZWFyKHBsdCk6CiAgICBwbHQuY2xhKCkKICAgIHBsdC5jbGYoKQogICAgcGx0LmNsb3NlKCkgCgpkZWYgZGVzY3JpYmUoCiAgICBjb250ZXh0OiBNTENsaWVudEN0eCwKICAgIHRhYmxlOiBVbmlvbltEYXRhSXRlbSwgc3RyXSwKICAgIGxhYmVsX2NvbHVtbjogc3RyLAogICAgY2xhc3NfbGFiZWxzOiBMaXN0W3N0cl0gPSBOb25lLAogICAga2V5OiBzdHIgPSAidGFibGUtc3VtbWFyeSIsCiAgICBwbG90X2hpc3Q6IGJvb2wgPSBUcnVlLAogICAgcGxvdHNfZGVzdDogc3RyID0gJ3Bsb3RzJwopIC0+IE5vbmU6CiAgICAiIiJTdW1tYXJpemUgYSB0YWJsZQoKICAgIFRPRE86IG1lcmdlIHdpdGggZGFzayB2ZXJzaW9uCgogICAgOnBhcmFtIGNvbnRleHQ6ICAgICAgICAgdGhlIGZ1bmN0aW9uIGNvbnRleHQKICAgIDpwYXJhbSB0YWJsZTogICAgICAgICAgIHBhbmRhcyBkYXRhZnJhbWUKICAgIDpwYXJhbSBsYWJlbF9jb2x1bW46ICAgIGdyb3VuZCB0cnV0aCBjb2x1bW4gbGFiZWwKICAgIDpwYXJhbSBrZXk6ICAgICAgICAgICAgIGtleSBvZiB0YWJsZSBzdW1tYXJ5IGluIGFydGlmYWN0IHN0b3JlCiAgICA6cGFyYW0gcGxvdF9oaXN0OiAgICAgICAoVHJ1ZSkgc2V0IHRoaXMgdG8gRmFsc2UgZm9yIGxhcmdlIHRhYmxlcwogICAgOnBhcmFtIHBsb3RzX2Rlc3Q6ICAgICAgZGVzdGluYXRpb24gZm9sZGVyIG9mIHN1bW1hcnkgcGxvdHMgKHJlbGF0aXZlIHRvIGFydGlmYWN0X3BhdGgpCiAgICAiIiIKICAgIGJhc2VfcGF0aCA9IGNvbnRleHQuYXJ0aWZhY3RfcGF0aAogICAgb3MubWFrZWRpcnMoYmFzZV9wYXRoLCBleGlzdF9vaz1UcnVlKQogICAgb3MubWFrZWRpcnMob3MucGF0aC5qb2luKGJhc2VfcGF0aCwgcGxvdHNfZGVzdCksIGV4aXN0X29rPVRydWUpCiAgICAKICAgIHRhYmxlID0gcGQucmVhZF9wYXJxdWV0KHN0cih0YWJsZSkpCiAgICBoZWFkZXIgPSB0YWJsZS5jb2x1bW5zLnZhbHVlcwoKICAgIF9nY2ZfY2xlYXIocGx0KQogICAgc25zcGx0ID0gc25zLnBhaXJwbG90KHRhYmxlLCBodWU9bGFiZWxfY29sdW1uKQogICAgc25zcGx0LnNhdmVmaWcob3MucGF0aC5qb2luKGJhc2VfcGF0aCwgZiJ7cGxvdHNfZGVzdH0vaGlzdC5wbmciKSkKICAgIGNvbnRleHQubG9nX2FydGlmYWN0KFBsb3RBcnRpZmFjdCgiaGlzdG9ncmFtcyIsICBib2R5PXBsdC5nY2YoKSksIGxvY2FsX3BhdGg9ZiJ7cGxvdHNfZGVzdH0vaGlzdC5odG1sIikKICAgIAogICAgc3VtdGJsID0gdGFibGUuZGVzY3JpYmUoKQogICAgc3VtdGJsID0gc3VtdGJsLmFwcGVuZChsZW4odGFibGUuaW5kZXgpLXRhYmxlLmNvdW50KCksIGlnbm9yZV9pbmRleD1UcnVlKQogICAgc3VtdGJsLmluc2VydCgwLCAibWV0cmljIiwgWyJjb3VudCIsICJtZWFuIiwgInN0ZCIsICJtaW4iLCIyNSUiLCAiNTAlIiwgIjc1JSIsICJtYXgiLCAibmFucyJdKQogICAgCiAgICBzdW10YmwudG9fY3N2KG9zLnBhdGguam9pbihiYXNlX3BhdGgsIGtleSsiLmNzdiIpLCBpbmRleD1GYWxzZSkKICAgIGNvbnRleHQubG9nX2FydGlmYWN0KGtleSwgbG9jYWxfcGF0aD1rZXkrIi5jc3YiKQoKICAgIF9nY2ZfY2xlYXIocGx0KQogICAgCiAgICBsYWJlbHMgPSB0YWJsZS5wb3AobGFiZWxfY29sdW1uKQogICAgY2xhc3NfYmFsYW5jZV9tb2RlbCA9IENsYXNzQmFsYW5jZShsYWJlbHM9Y2xhc3NfbGFiZWxzKQogICAgY2xhc3NfYmFsYW5jZV9tb2RlbC5maXQobGFiZWxzKQogICAgCiAgICBzY2FsZV9wb3Nfd2VpZ2h0ID0gY2xhc3NfYmFsYW5jZV9tb2RlbC5zdXBwb3J0X1swXS9jbGFzc19iYWxhbmNlX21vZGVsLnN1cHBvcnRfWzFdCiAgICBjb250ZXh0LmxvZ19hcnRpZmFjdCgic2NhbGVfcG9zX3dlaWdodCIsIGYie3NjYWxlX3Bvc193ZWlnaHQ6MC4yZn0iKQoKICAgIGNsYXNzX2JhbGFuY2VfbW9kZWwuc2hvdyhvdXRwYXRoPW9zLnBhdGguam9pbihiYXNlX3BhdGgsIGYie3Bsb3RzX2Rlc3R9L2ltYmFsYW5jZS5wbmciKSkKICAgIGNvbnRleHQubG9nX2FydGlmYWN0KFBsb3RBcnRpZmFjdCgiaW1iYWxhbmNlIiwgYm9keT1wbHQuZ2NmKCkpLCBsb2NhbF9wYXRoPWYie3Bsb3RzX2Rlc3R9L2ltYmFsYW5jZS5odG1sIikKICAgIAogICAgX2djZl9jbGVhcihwbHQpCiAgICB0Ymxjb3JyID0gdGFibGUuY29ycigpCiAgICBheCA9IHBsdC5heGVzKCkKICAgIHNucy5oZWF0bWFwKHRibGNvcnIsIGF4PWF4LCBhbm5vdD1GYWxzZSwgY21hcD1wbHQuY20uUmVkcykKICAgIGF4LnNldF90aXRsZSgiZmVhdHVyZXMgY29ycmVsYXRpb24iKQogICAgcGx0LnNhdmVmaWcob3MucGF0aC5qb2luKGJhc2VfcGF0aCwgZiJ7cGxvdHNfZGVzdH0vY29yci5wbmciKSkKICAgIGNvbnRleHQubG9nX2FydGlmYWN0KFBsb3RBcnRpZmFjdCgiY29ycmVsYXRpb24iLCAgYm9keT1wbHQuZ2NmKCkpLCBsb2NhbF9wYXRoPWYie3Bsb3RzX2Rlc3R9Y29yci5odG1sIikKICAgIAogICAKICAgIF9nY2ZfY2xlYXIocGx0KQoK
    commands: []
    code_origin: https://github.com/mlrun/functions.git#b0ba922e10fa0af2fcf2e04cce51eb7d9243bf25:describe/describe.ipynb
```

And the following task:
```
summ_task = NewTask(
    "sum", 
    handler="describe",  
    params={"key": "summary", 
            "label_column": "is_error", 
            'class_labels': ['0', '1'],
            'plot_hist': True,
            'plot_dest': 'plots'},
    inputs={"table": os.path.join(project_dir, 'data', 'aggregate.pq')},
    artifact_path=ARTIFACT_PATH)
```
